In [23]:
import numpy as np
from PIL import Image 
import glob

In [24]:
image_list =[]
resized_image=[]

In [25]:
for file_name in glob.glob('C:/Users/Hamza pc/*.jpg'):
    print(file_name)
    img=Image.open(file_name)
    image_list.append(img)

C:/Users/Hamza pc\car.jpg
C:/Users/Hamza pc\car1.jpg
C:/Users/Hamza pc\car2.jpg
C:/Users/Hamza pc\car3.jpg
C:/Users/Hamza pc\car4.jpg
C:/Users/Hamza pc\car5.jpg
C:/Users/Hamza pc\car6.jpg
C:/Users/Hamza pc\car7.jpg
C:/Users/Hamza pc\chrome.jpg
C:/Users/Hamza pc\pic1.jpg
C:/Users/Hamza pc\pic10.jpg
C:/Users/Hamza pc\pic11.jpg
C:/Users/Hamza pc\pic12.jpg
C:/Users/Hamza pc\pic13.jpg
C:/Users/Hamza pc\pic14.jpg
C:/Users/Hamza pc\pic2.jpg
C:/Users/Hamza pc\pic3.jpg
C:/Users/Hamza pc\pic4.jpg
C:/Users/Hamza pc\pic5.jpg
C:/Users/Hamza pc\pic6.jpg
C:/Users/Hamza pc\pic7.jpg
C:/Users/Hamza pc\pic8.jpg
C:/Users/Hamza pc\pic9.jpg


In [26]:
for image in image_list:
    image=image.resize((200,200))
    resized_image.append(image)

In [27]:
for (i,new) in enumerate(resized_image):
    new.save('{}{}{}'.format('C:/Users/Hamza pc/Desktop/Images/Re_images',i+1,'.jpg'))

In [28]:
for img1 in resized_image: 
    new_image=np.array(img1)

In [29]:
print(new_image.shape)
print(new_image.size)
print(new_image[:,:2])

(200, 200, 3)
120000
[[[251 255 255]
  [251 255 255]]

 [[251 255 255]
  [251 255 255]]

 [[251 255 255]
  [251 255 255]]

 ...

 [[  6  24  36]
  [  6  24  36]]

 [[  6  24  36]
  [  6  24  36]]

 [[  6  24  36]
  [  6  24  36]]]
